const User = require("./UserV2.model");
const Movie = require("./MovieV2.model");
const Slide = require("./Slide.model");
const Genre = require("./Genre.model");
const Country = require("./Country.model");
const Comment = require("./Comment.model");
const Episode = require("./Episode.model");
const News = require("./News.model");
module.exports = { User, Movie, Slide, Genre, Country, Comment, Episode, News };
